export const coursesData = [
  {
    "id": 1,
    "title": "Canvas Network",
    "url": "https://www.canvas.net/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Английский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 2,
    "title": "PROMETHEUS",
    "url": "https://prometheus.org.ua/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Украинский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 3,
    "title": "Основи цифрового маркетингу",
    "url": "https://learndigital.withgoogle.com/digitalworkshop-ua/course/digital-marketing",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Украинский",
    "theme": "Интернет-маркетинг",
    "comments": "",
    "course": true
  },
  {
    "id": 4,
    "title": "Проджект менеджмент 101",
    "url": "https://pmclub.pro/courses/pm-101",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Проджект-менеджмент",
    "comments": "",
    "course": true
  },
  {
    "id": 5,
    "title": "LinkedIn Learning",
    "url": "https://www.linkedin.com/learning/",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Английский",
    "theme": "Разное",
    "comments": "*Бесплатный доступ новым пользователям на 1 месяц.",
    "course": true
  },
  {
    "id": 6,
    "title": "Open University",
    "url": "https://www.open.edu/openlearn/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Английский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 7,
    "title": "freeCodeCamp",
    "url": "https://www.freecodecamp.org/learn",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Английский",
    "theme": "Программирование",
    "comments": "",
    "course": true
  },
  {
    "id": 8,
    "title": "BUSINESS ANALYSIS ESSENTIALS",
    "url": "https://e-5.com.ua/ru/trainings/besplatnyj-onlajn-kurs-business-analytics-essentials/",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Украинский",
    "theme": "Бизнес-аналитика",
    "comments": "",
    "course": true
  },
  {
    "id": 9,
    "title": "Основы баз данных (SQL)",
    "url": "https://www.spalah.com/course/sql",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Базы данных",
    "comments": "",
    "course": true
  },
  {
    "id": 10,
    "title": "Educational Era",
    "url": "https://www.ed-era.com/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Украинский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 11,
    "title": "SkillShare",
    "url": "https://www.skillshare.com/",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Английский",
    "theme": "Разное",
    "comments": "*Бесплатный доступ новым пользователям на 2 месяца.",
    "course": true
  },
  {
    "id": 12,
    "title": "Курс поработе в Figma",
    "url": "https://tildoshnaya.pro/figma-free-course",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Дизайн",
    "comments": "",
    "course": true
  },
  {
    "id": 13,
    "title": "Курс по фрилансу для дизайнеров",
    "url": "https://tildoshnaya.pro/freefreelance",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Фриланс",
    "comments": "",
    "course": true
  },
  {
    "id": 14,
    "title": "Skillbox",
    "url": "https://start.skillbox.ru/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 15,
    "title": "Дизайнер на Tilda",
    "url": "https://contented.ru/edu/tilda_covid/",
    "number": "Один",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Дизайн",
    "comments": "*Бесплатно до конца карантина.",
    "course": true
  },
  {
    "id": 16,
    "title": "Дизайн-библиотека",
    "url": "https://bangbangeducation.ru/subscription",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Дизайн",
    "comments": "Бесплатно до 17 апреля.",
    "course": true
  },
  {
    "id": 17,
    "title": "Курс по инвестициям для начинающих",
    "url": "https://journal.tinkoff.ru/pro/invest/#/",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Финансы",
    "comments": "",
    "course": true
  },
  {
    "id": 18,
    "title": "Курсы от Постнауки",
    "url": "https://postnauka.ru/courses",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 19,
    "title": "История кино в 10 фильмах",
    "url": "https://online.synchronize.ru/cinema_films",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Кино",
    "comments": "",
    "course": true
  },
  {
    "id": 20,
    "title": "Nikon School",
    "url": "https://online.nikonschool.com/courses/",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Английский",
    "theme": "Фотография",
    "comments": "*Бесплатно до конца апреля.",
    "course": true
  },
  {
    "id": 21,
    "title": "Освітні серіали",
    "url": "https://osvita.diia.gov.ua/courses",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Украинский",
    "theme": "Цифровое образование",
    "comments": "",
    "course": true
  },
  {
    "id": 22,
    "title": "Alison Courses",
    "url": "https://alison.com/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Английский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 23,
    "title": "ITVDN",
    "url": "https://itvdn.com/ru/shares/free-courses2020",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Программирование",
    "comments": "*До 30 апреля бесплатно можно выбрать 1 курс. Только для школьников и студентов!",
    "course": true
  },
  {
    "id": 24,
    "title": "edX",
    "url": "https://www.edx.org/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Английский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 25,
    "title": "Python для анализа данных",
    "url": "https://skillfactory.ru/python_free_covid/?utm_source=landing&utm_medium=site&utm_campaign=np_py_landing_all_lm_covid&utm_content=covid&_ga=2.202826449.1308663042.1586186790-147345352.1586186790",
    "number": "Один",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Аналитика",
    "comments": "*Бесплатно до конца карантина",
    "course": true
  },
  {
    "id": 26,
    "title": "Learn SQL and Excel for Data Analysis",
    "url": "http://datamonkey.pro/courses/",
    "number": "Два",
    "cost": "Бесплатно",
    "language": "Английский",
    "theme": "Аналитика",
    "comments": "",
    "course": true
  },
  {
    "id": 27,
    "title": "Тренажердля начинающих в\nData Science",
    "url": "https://skillfactory.ru/micro_dst/?utm_source=landing&utm_medium=site&utm_campaign=np__landing_all_lm_covid&utm_content=covid&_ga=2.231596639.1308663042.1586186790-147345352.1586186790",
    "number": "Один",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Data Science",
    "comments": "*Бесплатно до конца карантина",
    "course": true
  },
  {
    "id": 28,
    "title": "Курсы Интернет-маркетинга",
    "url": "https://www.cybermarketing.ru/video-courses.html",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Интернет-маркетинг",
    "comments": "",
    "course": true
  },
  {
    "id": 29,
    "title": "МегаФон Образование",
    "url": "https://education.megafon.ru/courses",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 30,
    "title": "Insta-карантин",
    "url": "https://universitybu.top/freekarantin?utm_source=covid",
    "number": "Один",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Интернет-маркетинг",
    "comments": "*Бесплатно до конца апреля.",
    "course": true
  },
  {
    "id": 31,
    "title": "Онлайн-обучение интернет‑маркетингу, курсы SEO",
    "url": "https://1ps.ru/courses/archive/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Интернет-маркетинг",
    "comments": "",
    "course": true
  },
  {
    "id": 32,
    "title": "История искусства\nв 10 шедеврах",
    "url": "https://online.synchronize.ru/10paint",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Искусство",
    "comments": "",
    "course": true
  },
  {
    "id": 33,
    "title": "100 лет фотографии",
    "url": "https://levelvan.ru/edu/photohistory",
    "number": "Один",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Фотография",
    "comments": "*Бесплатно по промокоду KARANTIN",
    "course": true
  },
  {
    "id": 34,
    "title": "Русская живопись: от Перова до Серова",
    "url": "https://levelvan.ru/edu/perovserov",
    "number": "Один",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Искусство",
    "comments": "*Бесплатно по промокоду KARANTIN",
    "course": true
  },
  {
    "id": 35,
    "title": "Открытое образование",
    "url": "https://openedu.ru/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 36,
    "title": "Stepik",
    "url": "https://stepik.org/catalog",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 37,
    "title": "Лекторий Московского физико-технического института",
    "url": "https://lectoriy.mipt.ru/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 38,
    "title": "Универсариум",
    "url": "https://universarium.org/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 39,
    "title": "Khan Academy",
    "url": "https://ru.khanacademy.org/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 40,
    "title": "Курсы от ВОЗ",
    "url": "https://openwho.org/courses",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский/Английский/Другие",
    "theme": "Здоровье",
    "comments": "",
    "course": true
  },
  {
    "id": 41,
    "title": "Интуит",
    "url": "https://www.intuit.ru/studies/courses?page=1",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 42,
    "title": "Treehouse",
    "url": "https://teamtreehouse.com/subscribe/plans?trial=yes",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Английский",
    "theme": "Программирование",
    "comments": "*Бесплатно первые 7 дней.",
    "course": true
  },
  {
    "id": 43,
    "title": "Microsoft Learn",
    "url": "https://docs.microsoft.com/ru-ru/learn/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 44,
    "title": "GeekBrains",
    "url": "https://geekbrains.ru/courses?tab=free#free",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Программирование",
    "comments": "",
    "course": true
  },
  {
    "id": 45,
    "title": "Otus",
    "url": "https://otus.ru/online/",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Программирование",
    "comments": "*Цена 1 рубль.",
    "course": true
  },
  {
    "id": 46,
    "title": "Python для начинающих",
    "url": "https://skillfactory.ru/micro_python/?utm_source=landing&utm_medium=site&utm_campaign=np__landing_all_lm_covid&utm_content=covid&_ga=2.229085020.1308663042.1586186790-147345352.1586186790",
    "number": "Один",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Программирование",
    "comments": "Бесплатно до конца карантина.",
    "course": true
  },
  {
    "id": 47,
    "title": "Онлайн-школа городских предпринимателей",
    "url": "https://vector.education/courses",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Бизнес",
    "comments": "",
    "course": true
  },
  {
    "id": 48,
    "title": "Курс для предпринимателей от Сбербанка",
    "url": "https://bc2.business-class.pro/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Бизнес",
    "comments": "",
    "course": true
  },
  {
    "id": 49,
    "title": "ПЕРВЫЙ ЛИДЕР-КОНСТРУКТОР",
    "url": "https://skillgo.ru/",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Бизнес",
    "comments": "",
    "course": true
  },
  {
    "id": 50,
    "title": "Применение Big Data в бизнесе",
    "url": "https://skillfactory.ru/bd_micro/?utm_source=landing&utm_medium=site&utm_campaign=np__landing_all_lm_covid&utm_content=covid&_ga=2.165538175.1308663042.1586186790-147345352.1586186790",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Data Science",
    "comments": "",
    "course": true
  },
  {
    "id": 51,
    "title": "Напишите свой первый код на PYTHON",
    "url": "https://sfcourses.com/pythonfree",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Программирование",
    "comments": "",
    "course": true
  },
  {
    "id": 52,
    "title": "Погрузись в мир финансов",
    "url": "https://sfcourses.com/financefree",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Финансы",
    "comments": "",
    "course": true
  },
  {
    "id": 53,
    "title": "Кейсы и консалтинг",
    "url": "https://sfcourses.com/consultingfree",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Консалтинг",
    "comments": "",
    "course": true
  },
  {
    "id": 54,
    "title": "Аналитика с Excel",
    "url": "https://sfcourses.com/excelfree",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Аналитика",
    "comments": "",
    "course": true
  },
  {
    "id": 55,
    "title": "Трейдинг и личные инвестиции",
    "url": "https://sfcourses.com/tradinvestfree",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Финансы",
    "comments": "",
    "course": true
  },
  {
    "id": 56,
    "title": "Список бесплатных курсов от Coursera",
    "url": "https://www.classcentral.com/report/coursera-free-certificate-covid-19/",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Английский",
    "theme": "Разное",
    "comments": "*Бесплатно до 31.05, ограниченное количество курсов.",
    "course": true
  },
  {
    "id": 57,
    "title": "DEEP LEARNING НА ПАЛЬЦАХ",
    "url": "https://dlcourse.ai/",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Machine learning",
    "comments": "",
    "course": true
  },
  {
    "id": 58,
    "title": "365 Data Science",
    "url": "https://365datascience.com/pricing/",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Английский",
    "theme": "Data Science",
    "comments": "*Бесплатно до 15.04",
    "course": true
  },
  {
    "id": 59,
    "title": "busuu",
    "url": "https://www.busuu.com/en/keep-kids-learning",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Английский",
    "theme": "Языки",
    "comments": "",
    "course": true
  },
  {
    "id": 60,
    "title": "LinguaLeo",
    "url": "https://lingualeo.com/ru/dashboard",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Языки",
    "comments": "",
    "course": true
  },
  {
    "id": 61,
    "title": "Duolingo",
    "url": "https://ru.duolingo.com/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Языки",
    "comments": "",
    "course": true
  },
  {
    "id": 62,
    "title": "Как не сойти с ума, работая из дома",
    "url": "https://www.mann-ivanov-ferber.ru/courses/home-office-vebinars/",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Бизнес",
    "comments": "",
    "course": true
  },
  {
    "id": 63,
    "title": "ВУМ online",
    "url": "https://vumonline.ua/",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Украинский",
    "theme": "Разное",
    "comments": "",
    "course": true
  },
  {
    "id": 64,
    "title": "Видеокурсы от Михаила Русакова",
    "url": "https://blog.myrusakov.ru/courses.html",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Русский",
    "theme": "Программирование",
    "comments": "*После списка платных курсов можно найти перечень бесплатного материала.",
    "course": true
  },
  {
    "id": 65,
    "title": "Introduction to SQL",
    "url": "https://www.datacamp.com/courses/introduction-to-sql",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Английский",
    "theme": "Базы данных",
    "comments": "",
    "course": true
  },
  {
    "id": 66,
    "title": "Бесплатное бизнес-образование",
    "url": "http://www.businesslearning.ru",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Бизнес",
    "comments": "",
    "course": true
  },
  {
    "id": 67,
    "title": "LoftSchool",
    "url": "https://loftschool.com",
    "number": "Много",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Программирование",
    "comments": "",
    "course": true
  },
  {
    "id": 68,
    "title": "Codeacademy",
    "url": "https://www.codecademy.com/catalog/subject/all",
    "number": "Много",
    "cost": "Бесплатно*",
    "language": "Английский",
    "theme": "Программирование",
    "comments": "*Часть курсов бесплатна.",
    "course": true
  },
  {
    "id": 69,
    "title": "Learn to code websites in HTML, CSS, and JS",
    "url": "https://dash.generalassemb.ly",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Английский",
    "theme": "Программирование",
    "comments": "",
    "course": true
  },
  {
    "id": 70,
    "title": "ReactJS Start. 10 дней прокачки",
    "url": "https://wep.wf/ksapin?traffic_mark=rkwquo",
    "number": "Один",
    "cost": "Бесплатно",
    "language": "Русский",
    "theme": "Программирование",
    "comments": "",
    "course": true
  }
]